### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by datrhi** [ericlove02/Valorant-Bot#2]
i made a val aimbot color-base about 1 month ago, it still work good.
I have something after 15 minutes look at this project.
1st, you will can not move mouse with mouse module in python or any other mouse driver. Riot block them, so u can not move your mouse follow signal from capture. 
2nd, I used python to process image too, but i just make a pixel search func to find out enemy so it quite simple. I excited with your method, then if u want to have a talk, pm me, i can tell u how to move mouse in valorant.
Discord: feeder #4583

**Comment by ericlove02** [comment]
I had some ideas for moving the mouse, then current libraries I am using were being tested on YouTube videos of Valorant gameplay so I could see if the coordinates were right. Also the images processing I am using is having trouble right now, I haven't trained a very good cascade model yet. I will PM you

**Comment by iHafez** [comment]
add me on disocrd i have a trained model its kinda good
Hafez#0877 @ericlove02

**Comment by ericlove02** [comment]
Project is not finished
